import Head from 'next/head'
import React from 'react';
import Container from 'react-bootstrap/Container';
import Header from '../components/Header'
import Layout from '../components/Layout';

export default function Home() {
  return(
    <>
      <Head>
        <title>Mercado Libre</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0" />
      </Head>
        <Layout>    
        </Layout>
    </>
  )
}
