import Head from 'next/head'
import React from 'react';
import Container from 'react-bootstrap/Container';
import Header from '../components/Header'
import Layout from '../components/Layout';

export default function Home() {
  return(
    <>
      <Head>
        <title>Mercado Libre</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <Layout>    
        </Layout>
    </>
  )
}
