import Head from 'next/head'
import React from 'react';
import Header from '../components/Header'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Mercado Libre</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
    </div>
  )
}
